Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Models/MojiModeli/Predbiljezba.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;

namespace SeminarskiRad.Models.MojiModeli
{
    public class Predbiljezba
    {
        [Key]
        public int IdPredbiljezba { get; set; }
        [Required(ErrorMessage = "Datum je obvezan")]
        [DataType(DataType.DateTime,ErrorMessage ="Ovo nije valjani datum")]
        public DateTime Datum { get; set; }
        [Required(ErrorMessage = "Ime je obvezno")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Prezime je obvezno")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Adresa je obvezna")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Korisnik je obvezan")]
        [EmailAddress(ErrorMessage ="Ovo nije valjana email adresa")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Broj telefona je obvezan")]
        public string Telefon { get; set; } 
        [Required(ErrorMessage ="Morate odrediti status"),Range(0,2,ErrorMessage ="Vrijednost mora biti: 0(neobrađen),1(prihvaćen) ili 2(odbijen)")]
        public int Status { get; set; }


        [Display(Name = "Seminar")]
        public int IdSeminar { get; set; }
        [ForeignKey("IdSeminar")]
        public virtual Seminar Seminar { get; set; }


        public Predbiljezba()
        {
            this.Datum = DateTime.Now;
            this.Status = 0;
        }
    }
  
}

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Models/MojiModeli/ViewModeli/StvoriSeminar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SeminarskiRad.Models.MojiModeli.ViewModeli
{
    public class StvoriSeminar
    {
        ApplicationDbContext db = new ApplicationDbContext();

        //Novi seminar
        public Seminar Seminar { get; set; }
        //Popis predavača
        public IEnumerable<SelectListItem> Predavaci { get; set; }

        public StvoriSeminar()
        {
            this.Seminar = new Seminar();
            this.Predavaci = db.Zaposlenici.Select(x => new SelectListItem
            {
                Text = x.Ime + " " + x.Prezime,
                Value = x.IdZaposlenik.ToString()
            });
        }
    }
}

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Controllers/MojiKontroleri/PocetakController.cs
using Microsoft.Ajax.Utilities;
using SeminarskiRad.Models;
using SeminarskiRad.Models.MojiModeli;
using SeminarskiRad.Models.MojiModeli.ViewModeli;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Odbc;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace SeminarskiRad.Controllers.MojiKontroleri
{
    [Authorize]
    public class PocetakController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        #region POPIS SEMINARA I UNOS PODATAKA -- ANON

        // Home
        [AllowAnonymous]
        public ActionResult Predbiljezba()
        {
            //Popis Seminara koji nisu popunjeni

            List<Seminar> PopisAktivnihSeminara = new List<Seminar>();
            PopisAktivnihSeminara = db.Seminari.Where(u => u.Popunjen == false).ToList();


            //Popis Predavača

            List<Zaposlenik> Predavaci = new List<Zaposlenik>();
            Predavaci = db.Zaposlenici.ToList();
            ViewBag.ImenaPredavaca = Predavaci;

            return View(PopisAktivnihSeminara);
        }
        [HttpPost]
        public ActionResult Predbiljezba(string Pretraga)
        {
                              
            //Popis Seminara koji nisu popunjeni

            List<Seminar> PopisAktivnihSeminara = new List<Seminar>();
            PopisAktivnihSeminara = db.Seminari.Where(u => u.Popunjen == false).ToList();


            //Seminari se pretražuju po datumu. Ako je datum prazan prikaže ih sve

            var DohvaceniSeminari = (from seminar in db.Seminari
                                     select seminar);
            
            if (!Pretraga.IsNullOrWhiteSpace())
            {
                if(Pretraga.IsDateTime())
                {
                  DateTime PretrazenDatum = DateTime.Parse(Pretraga);
                    DohvaceniSeminari = DohvaceniSeminari.Where(m => m.Datum.Year == PretrazenDatum.Year && m.Datum.Month == PretrazenDatum.Month && m.Datum.Day == PretrazenDatum.Day);
                }
                else
                {
                    DohvaceniSeminari = DohvaceniSeminari.Where(m => m.Naziv.Contains(Pretraga) || m.Opis.Contains(Pretraga) || m.Zaposlenik.Ime.Contains(Pretraga));
                }
            }
          
            

            //Popis Predavača

            List<Zaposlenik> Predavaci = new List<Zaposlenik>();
            Predavaci = db.Zaposlenici.ToList();
            ViewBag.ImenaPredavaca = Predavaci;

            return View(DohvaceniSeminari);
        }


        //Upis podataka Anona
        [AllowAnonymous]
        public ActionResult UnosOsobnihPodataka(int id)
        {
            //Naslov View-a

            ViewBag.ImeSeminara = db.Seminari.Where(x => x.IdSeminar == id).FirstOrDefault().Naziv;
           
            TempData["IdSeminara"] = id;

            return View(new Predbiljezba());

        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult UnosOsobnihPodataka(Predbiljezba predbiljezba)
        {
            predbiljezba.Datum = DateTime.Now;
            predbiljezba.IdSeminar = (int)TempData["IdSeminara"];

            if (ModelState.IsValid)
            {
                db.Predbiljezbe.Add(predbiljezba);
                db.SaveChanges();
            }
            return RedirectToAction("Predbiljezba");
        }
#endregion

#region CRUD PREDBILJEŽBE 

        
        public ActionResult Predbiljezbe()
        {
            List<Predbiljezba> PopisNeobradjenihPredbiljezbi = new List<Predbiljezba>();

            PopisNeobradjenihPredbiljezbi = db.Predbiljezbe.Where(p => p.Status == 0).ToList();
            
            return View(PopisNeobradjenihPredbiljezbi);
        }

        [HttpPost]
        public ActionResult Predbiljezbe(string Pretraga, int Filter)
        {
            List<Seminar> PopisSeminara = new List<Seminar>();
            PopisSeminara = db.Seminari.ToList();

            // Filtriram seminare po statusu

            List<Predbiljezba> PopisPredbiljezbiPoFiltru = new List<Predbiljezba>();
            PopisPredbiljezbiPoFiltru = db.Predbiljezbe.Where(p => p.Status == Filter).ToList();


            var DohvacenePretrage = (from predbiljezba in db.Predbiljezbe select predbiljezba);

            if (!Pretraga.IsNullOrWhiteSpace())
            {
                if (Pretraga.IsDateTime())
                {
                    DateTime PretrazenDatum = DateTime.Parse(Pretraga);
                    DohvacenePretrage = DohvacenePretrage.Where(m => m.Datum.Year == PretrazenDatum.Year && m.Datum.Month == PretrazenDatum.Month && m.Datum.Day == PretrazenDatum.Day);
                }
                else
                {
                    DohvacenePretrage = DohvacenePretrage.Where(m => m.Adresa.Contains(Pretraga)
                    || m.Email.Contains(Pretraga) || m.Ime.Contains(Pretraga) || m.Prezime.Contains(Pretraga)
                    || m.Telefon.Contains(Pretraga) || m.Seminar.Naziv.Contains(Pretraga));
                }
            }
            

            //Sastavljam konačan popis spajanjem dva popisa

            List<Predbiljezba> KonacanPopis = new List<Predbiljezba>();

            foreach (Predbiljezba predbiljezba in PopisPredbiljezbiPoFiltru)
            {
                foreach (Predbiljezba predbiljezba1 in DohvacenePretrage)
                {
                    if (predbiljezba == predbiljezba1)
                    {
                        KonacanPopis.Add(predbiljezba);
                    }
                }
            }

            return View(KonacanPopis);
        }

        public ActionResult UrediPredbiljezbu(int id)
        {
            //Dobavljam predbilježbu
            Predbiljezba predbiljezba = new Predbiljezba();
            predbiljezba = db.Predbiljezbe.Where(u => u.IdPredbiljezba == id).FirstOrDefault();

            //Popis Seminara
            List<Seminar> seminari = new List<Seminar>();
            seminari = db.Seminari.ToList();

           // Riječnik za popis seminara
            var PopisSeminara = new Dictionary<int,string >
            { };

                foreach (Seminar item in seminari)
            {
                PopisSeminara.Add( item.IdSeminar,item.Naziv);            
            }

            ViewBag.PopisSeminara = new SelectList(PopisSeminara, "Key", "Value");
                 
            return View(predbiljezba);
        }

        [HttpPost]
        public ActionResult UrediPredbiljezbu(Predbiljezba predbiljezba)
        {
                            
            //Nema smisla da je datum stariji od ove godine, osigurava od iskakanja Error-a

            if (predbiljezba.Datum.CompareTo(DateTime.Parse("2020.01.01")) < 0)
            {
                predbiljezba.Datum = DateTime.Now;
            }


            if (ModelState.IsValid)
            {
                db.Entry(predbiljezba).State = EntityState.Modified;            
                db.SaveChanges();
            }
            return RedirectToAction("Predbiljezbe");
        }
#endregion

#region SEMINARI I CRUD OPERACIJE -- USER

        //Userov uvid u seminare
        public ActionResult Seminari()
        {
            //Koristim ViewModel - u kontruktoru se nalazi još informacija

            SeminarIBrojPolaznikaViewModel seminarIBrojPolaznikaViewModel = new SeminarIBrojPolaznikaViewModel();

            return View(seminarIBrojPolaznikaViewModel);
        }

        [HttpPost]
        public ActionResult Seminari(string Pretraga)
        {

            //Pretraga po nazivu
            if (!Pretraga.IsEmpty())
            {
                if (Pretraga.IsDateTime())
                {
                    DateTime PretragaPoDatumu = DateTime.Parse(Pretraga);
                    SeminarIBrojPolaznikaViewModel seminarIBrojPolaznikaViewModel = new SeminarIBrojPolaznikaViewModel()
                    {
                        SeminariUViewModelu = db.Seminari.Where(x => x.Datum.Year == PretragaPoDatumu.Year &&
                        x.Datum.Month == PretragaPoDatumu.Month && x.Datum.Day == PretragaPoDatumu.Day)                     
                    };
                    return View(seminarIBrojPolaznikaViewModel);
                }
                else
                {
                    SeminarIBrojPolaznikaViewModel seminarIBrojPolaznikaViewModel = new SeminarIBrojPolaznikaViewModel()
                    {

                        SeminariUViewModelu = db.Seminari.Where(x => x.Naziv.ToLower().Contains(Pretraga.ToLower()) ||
                        x.Opis.Contains(Pretraga) || x.Zaposlenik.Ime.Contains(Pretraga) || x.Zaposlenik.Prezime.Contains(Pretraga))
                    };
                    return View(seminarIBrojPolaznikaViewModel);
                }             
            }
            else
            {
                SeminarIBrojPolaznikaViewModel seminarIBrojPolaznikaViewModel = new SeminarIBrojPolaznikaViewModel();
                return View(seminarIBrojPolaznikaViewModel);
            }

        }

        public ActionResult UrediSeminar(int id)
        {
            Seminar seminar = new Seminar();
            seminar = db.Seminari.Where(u => u.IdSeminar == id).FirstOrDefault();

            //Koristim Viewbagove za ne-propery informacije - Predavač i Broj Polaznika

            ViewBag.BrojPolaznika = db.Predbiljezbe.Where(u => u.IdSeminar == id).Count();
            ViewBag.ImePredavaca = db.Zaposlenici.Where(u => u.IdZaposlenik == seminar.Predavac).FirstOrDefault().Ime + " "
                + db.Zaposlenici.Where(u => u.IdZaposlenik == seminar.Predavac).FirstOrDefault().Prezime;

            return View(seminar);
        }
        [HttpPost]
        public ActionResult UrediSeminar(Seminar seminar)
        {
            //Ista zaštita kao i prije - pogledati UrediPredbilježbu

            if (seminar.Datum.CompareTo(DateTime.Parse("2020.01.01")) < 0)

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Views/Pocetak/Predbiljezba.cshtml
@model IEnumerable<SeminarskiRad.Models.MojiModeli.Seminar>
 
@{
    ViewBag.Title = "Predbilježba";
}
<head>
    <style>
        table, th, tr, td {
            border: 1px ridge;
            height: 35px;
            text-align: left;
        }                
        tr:hover{background-color:linen}
    </style>
</head>
<div>
    
    @using (Html.BeginForm("Predbiljezba","Pocetak",FormMethod.Post))
    {
    <p style="margin-top:20px">
        Pretraga:
        @Html.TextBox("Pretraga")
        <input type="submit" name="Pretraga" value="Pretraži" />
    </p>

    }

</div>

<wbr />

<table class="table" >
    <tr>
        <th style="width:80px">

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th style="width:300px">
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th style="width:160px">
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Predavac)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td >
                @Html.ActionLink("Odaberi", "UnosOsobnihPodataka", new { id = item.IdSeminar })
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Datum)
            </td>

            @Html.HiddenFor(modelItem => item.Predavac)
            @foreach (SeminarskiRad.Models.MojiModeli.Zaposlenik zaposlenik in ViewBag.ImenaPredavaca)
            {
                if (zaposlenik.IdZaposlenik == item.Predavac)
                {
                    <td>
                        @zaposlenik.Ime @zaposlenik.Prezime
                    </td>
                }
            }

        </tr>
    }

</table>

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Views/Pocetak/Predbiljezbe.cshtml
@model IEnumerable<SeminarskiRad.Models.MojiModeli.Predbiljezba>
<head>
    <style>
        table, th, tr, td {
            border: 1px ridge;
           height:35px;
           text-align:center;
        }
        hover {
                background-color: linen
            }
    </style>
</head>
@{
    ViewBag.Title = "Predbilježbe";
}



@using (Html.BeginForm("Predbiljezbe", "Pocetak", FormMethod.Post))
{
    
        <div>
            <p style="margin-top:20px">
                Pretraga:
                @Html.TextBox("Pretraga")
                <input type="submit" value="Pretraži" />
            </p>           
        </div>
        <tr>          
            <td>
                @Html.Label("Neobrađene")
                @Html.RadioButton("Filter", 0, true)/
            </td>
            <td>
                @Html.Label("Prihvaćene")
                @Html.RadioButton("Filter", 1)/
            </td>
            <td>
                @Html.Label("Odbijene")
                @Html.RadioButton("Filter", 2)/
            </td>
        </tr>


        

}
<wbr />

<table>
    <tr >
        <th style="width:80px">

        </th>
        <th style="width:200px">
            @Html.DisplayNameFor(model => model.IdSeminar)
        </th>
        <th  style="width:80px">
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.Status)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td >
                @Html.ActionLink("Odaberi", "UrediPredbiljezbu", new { id = item.IdPredbiljezba }) 
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Seminar.Naziv)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Adresa)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.Telefon)
            </td>
            @{
                if (item.Status == 0)
                {
                    <td>
                        Neobrađen
                    </td>
                }
                else if (item.Status == 1)
                {
                    <td>
                        Prihvaćen
                    </td>
                }
                else if (item.Status == 2)
                {
                    <td>
                        Odbijen
                    </td>
                }
                else
                {
                    <td>
                        Nepravilan status
                    </td>
                }
            }

        </tr>
    }

</table>

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Views/Pocetak/Seminari.cshtml
@model SeminarskiRad.Models.MojiModeli.SeminarIBrojPolaznikaViewModel

@{
    ViewBag.Title = "SeminariUViewModelu";
}

<head>
    <style>
        table, th, tr, td {
            border: 1px ridge;
            height: 30px;
            text-align: center;
        }

        tr:hover {
            background-color: linen
        }
    </style>
</head>

<div style="margin-top:20px">

    @using (Html.BeginForm("Seminari", "Pocetak", FormMethod.Post))
    {
    <p>
        Pretraga:

        @Html.TextBox("Pretraga")
        <input type="submit" name="Pretraga" value="Pretraži" />

    </p>

    }

 </div>
<wbr />

<div style="margin-top:30px;margin-bottom:20px" >
    
    @Html.ActionLink("Novi", "StvoriSeminar", null, new {@class = "btn btn-primary"})
</div>
<wbr />

<table class="table">
    <tr>
        <th style="width:250px">

        </th>
        <th>
            Naziv
        </th>
        <th style="width:150px">
            Predavač
        </th>
        <th>
            Opis
        </th>
        <th style="width: 150px">
            Datum
        </th>
        <th style="width:50px">
            Popunjen
        </th>
        <th style="width:50px">
            Broj Polaznika
        </th>
    </tr>

    @foreach (SeminarskiRad.Models.MojiModeli.Seminar item in Model.SeminariUViewModelu)
    {
        <tr>
            <td>
                @Html.ActionLink("Uredi", "UrediSeminar", new { id = item.IdSeminar }) |
                @Html.ActionLink("Izbriši", "IzbrisiSeminar", new { id = item.IdSeminar }) |
                @Html.ActionLink("Promjeni predavača", "PromjeniPredavaca", "Admin", new { id = item.IdSeminar }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            @foreach (SeminarskiRad.Models.MojiModeli.Zaposlenik JedanOdZaposlenika in Model.PredavaciUViewModelu)
            {
                if (JedanOdZaposlenika.IdZaposlenik == item.Predavac)
                {
                    <td>
                        @JedanOdZaposlenika.Ime @JedanOdZaposlenika.Prezime
                    </td>
                }
            }
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Popunjen)
            </td>
            @foreach (SeminarskiRad.Models.MojiModeli.BrojPolaznika JedanOdBrojevaPolaznika in Model.BrojPolaznikaUViewModelu)
            {
                if (JedanOdBrojevaPolaznika.IdSeminara == item.IdSeminar)
                {
                    <td>
                        @JedanOdBrojevaPolaznika.BrojPolaznikaUKlasi
                    </td>
                }
            }

        </tr>
    }

</table>

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Views/Pocetak/StvoriSeminar.cshtml
@model SeminarskiRad.Models.MojiModeli.ViewModeli.StvoriSeminar

@{
    ViewBag.Title = "StvoriSeminar";
    
}

<h2>Stvori Seminar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Seminar.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seminar.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seminar.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Seminar.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Seminar.Opis, new { htmlAttributes = new { @class = "form-control", @style= "max-width" } })
                @Html.ValidationMessageFor(model => model.Seminar.Opis, "", new { @class = "text-danger" })
            </div>
        </div>
                
        
        <div class="form-group">
            @Html.LabelFor(model => model.Seminar.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seminar.Datum, new { htmlAttributes = new { @class = "form-control", @Value = @Model.Seminar.Datum.ToString("yyyy-MM-dd HH:mm") } })
                @Html.ValidationMessageFor(model => model.Seminar.Datum, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Seminar.Predavac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Seminar.Predavac, Model.Predavaci)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stvori" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @ViewBag.StvoriSeminar
</div>

<div>
    @Html.ActionLink("Nazad na popis seminara", "Seminari")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Seminarski Rad - Josip Šaban/Aplikacija/SeminarskiRad/Views/Pocetak/UnosOsobnihPodataka.cshtml
@model SeminarskiRad.Models.MojiModeli.Predbiljezba

@{
    ViewBag.Title = "UnosOsobnihPodataka";
    Html.EnableUnobtrusiveJavaScript();
    Html.EnableClientValidation();
}
    <h4>Molimo unesite osobne podatke za predbilježbu na seminar:</h4>
    <h2>@ViewBag.ImeSeminara</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
         </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Predbilježi se" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad na predbilježbu", "Predbiljezba")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}